services:
  web:
    image: nginx:1.29-alpine
    ports:
      - "5000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html

  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nyatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
